name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            platform: linux-amd64
            binary_name: fetchncache
          - goos: darwin
            goarch: arm64
            platform: darwin-arm64
            binary_name: fetchncache
          - goos: darwin
            goarch: amd64
            platform: darwin-amd64
            binary_name: fetchncache
          - goos: windows
            goarch: amd64
            platform: windows-amd64
            binary_name: fetchncache.exe

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
        cache: true
    
    - name: Build binary
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        mkdir -p ${{ matrix.platform }}
        go build -ldflags="-s -w -X main.version=${{ github.ref_name }}" -o ${{ matrix.platform }}/${{ matrix.binary_name }} ./cmd/fetchncache
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.platform }}
        path: ${{ matrix.platform }}/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
    
    - name: List downloaded files structure
      run: |
        echo "=== Complete directory structure ==="
        find . -type f -name "*fetchncache*" | sort
        echo "=== All directories ==="
        find . -type d | sort
    
    - name: Reorganize binaries
      run: |
        mkdir -p release-assets
        # Move all binaries to a flat structure with platform prefixes
        find . -name "fetchncache" -path "*/linux-amd64/*" -exec cp {} release-assets/fetchncache-linux-amd64 \;
        find . -name "fetchncache" -path "*/darwin-arm64/*" -exec cp {} release-assets/fetchncache-darwin-arm64 \;
        find . -name "fetchncache" -path "*/darwin-amd64/*" -exec cp {} release-assets/fetchncache-darwin-amd64 \;
        find . -name "fetchncache.exe" -path "*/windows-amd64/*" -exec cp {} release-assets/fetchncache-windows-amd64.exe \;
        echo "=== Release assets ==="
        ls -la release-assets/
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: release-assets/*
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}